Portfolio: mobile version
bekjon-me/microverse-portfolio pull request #1
Opened 2022-06-30 19:36 UTC by bekjon-me

- added header section
- added headline section

2022-06-30 20:08 UTC, isaacpitwa requested changes
Hi @bekjon-me 🙂 ,

You have done a tremendous job with setting up your portfolio mobile version. I really like it :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)


## Highlights 
- All linters are passing  ✅
- Correct use of GitHub flow ✅
- Well documented Repository ✅
-  Clean and readable code base ✅

## Required changes ♻️ 

Check the comments under the review.

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Check the comments under the review.





Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @isaacpitwa.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 20:08 UTC, isaacpitwa commented on index.html
> +        <div class="logo">My Logo</div>
Great job achieving the Toolbar 👏🏽.

- [ ] it would be useful to use a link i.e `a`  tag for the logo instead of a `div` tag. it helps users navigate back to the home page.

2022-07-01 07:44 UTC, tufoinnkuo10 requested changes
Hi @bekjon-me 

There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated

## Required Changes ♻️♻️
Check the comments under the review

![tufoin](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-07-01 07:44 UTC, tufoinnkuo10 commented on index.html
> +      <div class="logo">My Logo</div>
- [ ] like the previous reviewer noted, the logo should be raped inside an `a tag` so it serves as a link later on to the home page

2022-07-01 08:11 UTC, codecaiine approved these changes
Hi @bekjon-me , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

No linters errors :heavy_check_mark: 
Good use of GitHub flow :heavy_check_mark: 
Descriptive pull request :heavy_check_mark: 
Clean code :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 08:12 UTC, merged